import { test, expect } from '@playwright/test';

test('browser registration, check-in, seven tabs, payment settlement, invoice and timeline survive reload', async ({ page }) => {
  test.setTimeout(120000);
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/reception/register');
  await expect(page.getByRole('heading', { name: 'Patient registration' })).toBeVisible();
  await page.getByLabel('First Name', { exact: true }).fill('Browser');
  await page.getByLabel('Last Name', { exact: true }).fill('Journey');
  await page.getByLabel('Dob', { exact: true }).fill('1990-01-01');
  await page.getByLabel('Mobile', { exact: true }).fill('9000000042');
  await page.getByRole('button', { name: 'Save patient', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Browser Journey', exact: true })).toBeVisible();
  const profile = page.url();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Browser Journey', exact: true })).toBeVisible();
  await page.goto('/admin/settings');
  await page.getByLabel('Consultation fee (₹)', { exact: true }).fill('500');
  await page.getByLabel('Follow-up fee (₹)', { exact: true }).fill('300');
  await page.getByRole('button', { name: /Save/i }).first().click();
  await page.goto(profile);
  await page.getByRole('link', { name: 'Check in', exact: true }).click();
  await page.getByRole('checkbox', { name: /Pay now/ }).check();
  await page.getByRole('button', { name: 'Complete check-in', exact: true }).click();
  const encounter = (await page.getByTestId('generated-case-id').textContent())!;
  await page.reload();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('medflow-browser-state-v1')!));
  expect(stored.slices['doctor-billing'].state.payments).toHaveLength(1);
  await page.goto(`/doctor/consultation/${encounter}`);
  await page.getByRole('button', { name: 'Start consultation', exact: true }).click();
  await page.getByLabel('Chief complaint', { exact: true }).fill('Persistent rash');
  await page.getByLabel('examination', { exact: true }).fill('Recorded examination');
  for (const tab of ['2. Investigations', '3. Prescription', '4. Procedures', '5. Clinical Images']) await page.getByRole('button', { name: tab, exact: true }).click();
  await page.getByRole('button', { name: '6. Diagnosis', exact: true }).click();
  await page.getByLabel('finalDiagnosis', { exact: true }).fill('Recorded diagnosis');
  await page.getByLabel('followUpDate', { exact: true }).fill('2026-10-01');
  await page.reload();
  await expect(page.getByLabel('Chief complaint', { exact: true })).toHaveValue('Persistent rash');
  await page.getByRole('button', { name: '7. Final Summary', exact: true }).click();
  await expect(page.getByText('Diagnosis: Recorded diagnosis', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'End consultation', exact: true }).click();
  await page.getByRole('link', { name: 'Ready for billing', exact: true }).click();
  await page.getByLabel('Encounter', { exact: true }).selectOption(encounter);
  await expect(page.getByText('Outstanding ₹0.00', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Settle & finalize', exact: true }).click();
  await page.getByRole('link', { name: 'Open / print invoice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Invoice INV-/ })).toBeVisible();
  await page.reload();
  await expect(page.getByText('Balance: ₹0.00', { exact: true })).toBeVisible();
  await page.goto('/reception/billing');
  await page.getByLabel('Encounter', { exact: true }).selectOption(encounter);
  await page.getByRole('button', { name: 'Discharge & close encounter', exact: true }).click();
  await page.goto(profile); await page.reload();
  await expect(page.getByText(/ENCOUNTER CLOSED/)).toBeVisible();
  expect(errors).toEqual([]);
});
